// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package com.xgama.sockethttpconvert.pb;

public final class TypeClass {
  private TypeClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code sockethttpconvert.pb.Type}
   */
  public enum Type
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LAOHU_USER = 1;</code>
     */
    LAOHU_USER(0, 1),
    /**
     * <code>JY_USER = 2;</code>
     */
    JY_USER(1, 2),
    /**
     * <code>DL_USER = 3;</code>
     */
    DL_USER(2, 3),
    /**
     * <code>QH_USER = 4;</code>
     */
    QH_USER(3, 4),
    /**
     * <code>PP_USER = 5;</code>
     */
    PP_USER(4, 5),
    /**
     * <code>UC_USER = 6;</code>
     */
    UC_USER(5, 6),
    /**
     * <code>XM_USER = 7;</code>
     */
    XM_USER(6, 7),
    /**
     * <code>WDJ_USER = 8;</code>
     */
    WDJ_USER(7, 8),
    /**
     * <code>TBT_USER = 9;</code>
     */
    TBT_USER(8, 9),
    /**
     * <code>BDDK_USER = 10;</code>
     */
    BDDK_USER(9, 10),
    /**
     * <code>AZ_USER = 11;</code>
     */
    AZ_USER(10, 11),
    /**
     * <code>KY_USER = 12;</code>
     */
    KY_USER(11, 12),
    /**
     * <code>ITOOLS_USER = 15;</code>
     */
    ITOOLS_USER(12, 15),
    /**
     * <code>ONESDK_USER = 18;</code>
     */
    ONESDK_USER(13, 18),
    /**
     * <code>USER_VALIDATE_RESULT = 100;</code>
     */
    USER_VALIDATE_RESULT(14, 100),
    /**
     * <code>LAOHU_CHARGE = 101;</code>
     */
    LAOHU_CHARGE(15, 101),
    /**
     * <code>JY_CHARGE = 102;</code>
     */
    JY_CHARGE(16, 102),
    /**
     * <code>DL_CHARGE = 103;</code>
     */
    DL_CHARGE(17, 103),
    /**
     * <code>QH_CHARGE = 104;</code>
     */
    QH_CHARGE(18, 104),
    /**
     * <code>PP_CHARGE = 105;</code>
     */
    PP_CHARGE(19, 105),
    /**
     * <code>UC_CHARGE = 106;</code>
     */
    UC_CHARGE(20, 106),
    /**
     * <code>XM_CHARGE = 107;</code>
     */
    XM_CHARGE(21, 107),
    /**
     * <code>WDJ_CHARGE = 108;</code>
     */
    WDJ_CHARGE(22, 108),
    /**
     * <code>TBT_CHARGE = 109;</code>
     */
    TBT_CHARGE(23, 109),
    /**
     * <code>BDDK_CHARGE = 110;</code>
     */
    BDDK_CHARGE(24, 110),
    /**
     * <code>AZ_CHARGE = 111;</code>
     */
    AZ_CHARGE(25, 111),
    /**
     * <code>TM_CHARGE = 112;</code>
     */
    TM_CHARGE(26, 112),
    /**
     * <code>KY_CHARGE = 113;</code>
     */
    KY_CHARGE(27, 113),
    /**
     * <code>ITOOLS_CHARGE = 118;</code>
     */
    ITOOLS_CHARGE(28, 118),
    /**
     * <code>YY_CHARGE = 119;</code>
     */
    YY_CHARGE(29, 119),
    /**
     * <code>ONESDK_CHARGE = 124;</code>
     */
    ONESDK_CHARGE(30, 124),
    /**
     * <code>CHARGE_RESULT = 200;</code>
     */
    CHARGE_RESULT(31, 200),
    /**
     * <code>QH_GET_USER = 201;</code>
     */
    QH_GET_USER(32, 201),
    /**
     * <code>QH_GET_USER_RESULT = 202;</code>
     */
    QH_GET_USER_RESULT(33, 202),
    /**
     * <code>QH_REFRESH_TOKEN = 203;</code>
     */
    QH_REFRESH_TOKEN(34, 203),
    /**
     * <code>QH_REFRESH_TOKEN_RESULT = 204;</code>
     */
    QH_REFRESH_TOKEN_RESULT(35, 204),
    /**
     * <code>GOOGLE_PAY = 221;</code>
     */
    GOOGLE_PAY(36, 221),
    /**
     * <code>GOOGLE_PAY_CHARGE = 222;</code>
     */
    GOOGLE_PAY_CHARGE(37, 222),
    /**
     * <code>APPLE_CHARGE = 301;</code>
     */
    APPLE_CHARGE(38, 301),
    /**
     * <code>APPLE_CHARGE_RESULT = 400;</code>
     */
    APPLE_CHARGE_RESULT(39, 400),
    /**
     * <code>HEARTBEAT = 500;</code>
     */
    HEARTBEAT(40, 500),
    ;

    /**
     * <code>LAOHU_USER = 1;</code>
     */
    public static final int LAOHU_USER_VALUE = 1;
    /**
     * <code>JY_USER = 2;</code>
     */
    public static final int JY_USER_VALUE = 2;
    /**
     * <code>DL_USER = 3;</code>
     */
    public static final int DL_USER_VALUE = 3;
    /**
     * <code>QH_USER = 4;</code>
     */
    public static final int QH_USER_VALUE = 4;
    /**
     * <code>PP_USER = 5;</code>
     */
    public static final int PP_USER_VALUE = 5;
    /**
     * <code>UC_USER = 6;</code>
     */
    public static final int UC_USER_VALUE = 6;
    /**
     * <code>XM_USER = 7;</code>
     */
    public static final int XM_USER_VALUE = 7;
    /**
     * <code>WDJ_USER = 8;</code>
     */
    public static final int WDJ_USER_VALUE = 8;
    /**
     * <code>TBT_USER = 9;</code>
     */
    public static final int TBT_USER_VALUE = 9;
    /**
     * <code>BDDK_USER = 10;</code>
     */
    public static final int BDDK_USER_VALUE = 10;
    /**
     * <code>AZ_USER = 11;</code>
     */
    public static final int AZ_USER_VALUE = 11;
    /**
     * <code>KY_USER = 12;</code>
     */
    public static final int KY_USER_VALUE = 12;
    /**
     * <code>ITOOLS_USER = 15;</code>
     */
    public static final int ITOOLS_USER_VALUE = 15;
    /**
     * <code>ONESDK_USER = 18;</code>
     */
    public static final int ONESDK_USER_VALUE = 18;
    /**
     * <code>USER_VALIDATE_RESULT = 100;</code>
     */
    public static final int USER_VALIDATE_RESULT_VALUE = 100;
    /**
     * <code>LAOHU_CHARGE = 101;</code>
     */
    public static final int LAOHU_CHARGE_VALUE = 101;
    /**
     * <code>JY_CHARGE = 102;</code>
     */
    public static final int JY_CHARGE_VALUE = 102;
    /**
     * <code>DL_CHARGE = 103;</code>
     */
    public static final int DL_CHARGE_VALUE = 103;
    /**
     * <code>QH_CHARGE = 104;</code>
     */
    public static final int QH_CHARGE_VALUE = 104;
    /**
     * <code>PP_CHARGE = 105;</code>
     */
    public static final int PP_CHARGE_VALUE = 105;
    /**
     * <code>UC_CHARGE = 106;</code>
     */
    public static final int UC_CHARGE_VALUE = 106;
    /**
     * <code>XM_CHARGE = 107;</code>
     */
    public static final int XM_CHARGE_VALUE = 107;
    /**
     * <code>WDJ_CHARGE = 108;</code>
     */
    public static final int WDJ_CHARGE_VALUE = 108;
    /**
     * <code>TBT_CHARGE = 109;</code>
     */
    public static final int TBT_CHARGE_VALUE = 109;
    /**
     * <code>BDDK_CHARGE = 110;</code>
     */
    public static final int BDDK_CHARGE_VALUE = 110;
    /**
     * <code>AZ_CHARGE = 111;</code>
     */
    public static final int AZ_CHARGE_VALUE = 111;
    /**
     * <code>TM_CHARGE = 112;</code>
     */
    public static final int TM_CHARGE_VALUE = 112;
    /**
     * <code>KY_CHARGE = 113;</code>
     */
    public static final int KY_CHARGE_VALUE = 113;
    /**
     * <code>ITOOLS_CHARGE = 118;</code>
     */
    public static final int ITOOLS_CHARGE_VALUE = 118;
    /**
     * <code>YY_CHARGE = 119;</code>
     */
    public static final int YY_CHARGE_VALUE = 119;
    /**
     * <code>ONESDK_CHARGE = 124;</code>
     */
    public static final int ONESDK_CHARGE_VALUE = 124;
    /**
     * <code>CHARGE_RESULT = 200;</code>
     */
    public static final int CHARGE_RESULT_VALUE = 200;
    /**
     * <code>QH_GET_USER = 201;</code>
     */
    public static final int QH_GET_USER_VALUE = 201;
    /**
     * <code>QH_GET_USER_RESULT = 202;</code>
     */
    public static final int QH_GET_USER_RESULT_VALUE = 202;
    /**
     * <code>QH_REFRESH_TOKEN = 203;</code>
     */
    public static final int QH_REFRESH_TOKEN_VALUE = 203;
    /**
     * <code>QH_REFRESH_TOKEN_RESULT = 204;</code>
     */
    public static final int QH_REFRESH_TOKEN_RESULT_VALUE = 204;
    /**
     * <code>GOOGLE_PAY = 221;</code>
     */
    public static final int GOOGLE_PAY_VALUE = 221;
    /**
     * <code>GOOGLE_PAY_CHARGE = 222;</code>
     */
    public static final int GOOGLE_PAY_CHARGE_VALUE = 222;
    /**
     * <code>APPLE_CHARGE = 301;</code>
     */
    public static final int APPLE_CHARGE_VALUE = 301;
    /**
     * <code>APPLE_CHARGE_RESULT = 400;</code>
     */
    public static final int APPLE_CHARGE_RESULT_VALUE = 400;
    /**
     * <code>HEARTBEAT = 500;</code>
     */
    public static final int HEARTBEAT_VALUE = 500;


    public final int getNumber() { return value; }

    public static Type valueOf(int value) {
      switch (value) {
        case 1: return LAOHU_USER;
        case 2: return JY_USER;
        case 3: return DL_USER;
        case 4: return QH_USER;
        case 5: return PP_USER;
        case 6: return UC_USER;
        case 7: return XM_USER;
        case 8: return WDJ_USER;
        case 9: return TBT_USER;
        case 10: return BDDK_USER;
        case 11: return AZ_USER;
        case 12: return KY_USER;
        case 15: return ITOOLS_USER;
        case 18: return ONESDK_USER;
        case 100: return USER_VALIDATE_RESULT;
        case 101: return LAOHU_CHARGE;
        case 102: return JY_CHARGE;
        case 103: return DL_CHARGE;
        case 104: return QH_CHARGE;
        case 105: return PP_CHARGE;
        case 106: return UC_CHARGE;
        case 107: return XM_CHARGE;
        case 108: return WDJ_CHARGE;
        case 109: return TBT_CHARGE;
        case 110: return BDDK_CHARGE;
        case 111: return AZ_CHARGE;
        case 112: return TM_CHARGE;
        case 113: return KY_CHARGE;
        case 118: return ITOOLS_CHARGE;
        case 119: return YY_CHARGE;
        case 124: return ONESDK_CHARGE;
        case 200: return CHARGE_RESULT;
        case 201: return QH_GET_USER;
        case 202: return QH_GET_USER_RESULT;
        case 203: return QH_REFRESH_TOKEN;
        case 204: return QH_REFRESH_TOKEN_RESULT;
        case 221: return GOOGLE_PAY;
        case 222: return GOOGLE_PAY_CHARGE;
        case 301: return APPLE_CHARGE;
        case 400: return APPLE_CHARGE_RESULT;
        case 500: return HEARTBEAT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<Type>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Type>() {
            public Type findValueByNumber(int number) {
              return Type.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.xgama.sockethttpconvert.pb.TypeClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final Type[] VALUES = values();

    public static Type valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private Type(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:sockethttpconvert.pb.Type)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntype.proto\022\024sockethttpconvert.pb*\276\005\n\004T" +
      "ype\022\016\n\nLAOHU_USER\020\001\022\013\n\007JY_USER\020\002\022\013\n\007DL_U" +
      "SER\020\003\022\013\n\007QH_USER\020\004\022\013\n\007PP_USER\020\005\022\013\n\007UC_US" +
      "ER\020\006\022\013\n\007XM_USER\020\007\022\014\n\010WDJ_USER\020\010\022\014\n\010TBT_U" +
      "SER\020\t\022\r\n\tBDDK_USER\020\n\022\013\n\007AZ_USER\020\013\022\013\n\007KY_" +
      "USER\020\014\022\017\n\013ITOOLS_USER\020\017\022\017\n\013ONESDK_USER\020\022" +
      "\022\030\n\024USER_VALIDATE_RESULT\020d\022\020\n\014LAOHU_CHAR" +
      "GE\020e\022\r\n\tJY_CHARGE\020f\022\r\n\tDL_CHARGE\020g\022\r\n\tQH" +
      "_CHARGE\020h\022\r\n\tPP_CHARGE\020i\022\r\n\tUC_CHARGE\020j\022" +
      "\r\n\tXM_CHARGE\020k\022\016\n\nWDJ_CHARGE\020l\022\016\n\nTBT_CH",
      "ARGE\020m\022\017\n\013BDDK_CHARGE\020n\022\r\n\tAZ_CHARGE\020o\022\r" +
      "\n\tTM_CHARGE\020p\022\r\n\tKY_CHARGE\020q\022\021\n\rITOOLS_C" +
      "HARGE\020v\022\r\n\tYY_CHARGE\020w\022\021\n\rONESDK_CHARGE\020" +
      "|\022\022\n\rCHARGE_RESULT\020\310\001\022\020\n\013QH_GET_USER\020\311\001\022" +
      "\027\n\022QH_GET_USER_RESULT\020\312\001\022\025\n\020QH_REFRESH_T" +
      "OKEN\020\313\001\022\034\n\027QH_REFRESH_TOKEN_RESULT\020\314\001\022\017\n" +
      "\nGOOGLE_PAY\020\335\001\022\026\n\021GOOGLE_PAY_CHARGE\020\336\001\022\021" +
      "\n\014APPLE_CHARGE\020\255\002\022\030\n\023APPLE_CHARGE_RESULT" +
      "\020\220\003\022\016\n\tHEARTBEAT\020\364\003B+\n\036com.xgama.socketh" +
      "ttpconvert.pbB\tTypeClass"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
